services:
  app:
    image: europe-north1-docker.pkg.dev/rasmus-prod/st-workout/streamlit-app:${IMAGE_TAG}
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["streamlit", "run", "app.py", "--server.port=8080", "--server.headless=true"]
