name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - stg


env:
  STREAMLIT_ENV=${{ github.ref_name == 'main' && 'prod' || 'stg' }}
  IMAGE_TAG=${{ github.ref_name == 'main' && 'latest' || 'stg' }}
  GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker europe-north1-docker.pkg.dev

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Optional: verify installation

    - name: Build and push Docker image using Docker Compose
      run: |
        docker-compose --env-file .env -f docker-compose.yaml build
        docker-compose --env-file .env -f docker-compose.yaml push
