name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: rasmus-prod
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Optional: verify installation

    - name: Determine Environment and Create .env file
      run: |
        # Set environment variables based on the branch
        if [[ "${{ github.ref_name }}" == "main" ]]; then # Production environment
          echo "STREAMLIT_ENV=prod" >> .env
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> .env
          IMAGE_TAG="latest"
        elif [[ "${{ github.ref_name }}" == "stg" ]]; then # Staging environment
          echo "STREAMLIT_ENV=stg" >> .env
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> .env
          IMAGE_TAG="stg"
        else
          echo "Branch is not configured for deployment"
          exit 1
        fi

    - name: Build and push Docker image using Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
